turtlebot2: #namespace
    task_and_robot_environment_name: 'TurtleBot3World-v1'
    ros_ws_abspath: "/genesys2_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.8
    epsilon_discount: 0.999
    nepisodes: 2000
    nsteps: 10000000
    running_step: 0.06 # Time for each step
